import Progress from './progress'
import Mask from './mask'
import ItemHead from './itemHead'
import CodeInput from './codeInput'
import LoadMore from './loadMore'
import Header from './header'
import BackAvatar from './backAvatar'
import HomeBanner from './homeBanner'
// import SplashSwiper from './splashSwiper'
import NoNetwork from './noNetwork'
import HomeSearch from './homeSearch'
import LoginInput from './loginInput'
import Item from './item'
import IconCeil from './iconCeil'
import CardItem from './cardItem'
import PlayBtn from './playBtn'
import NewsFooter from './newsFooter'
import ButtonCeil from './buttonCeil'
import Share from './share'
export { Progress, Mask, ItemHead, CodeInput, LoadMore, Header, BackAvatar, HomeBanner, NoNetwork, HomeSearch, LoginInput, Item, IconCeil, CardItem, PlayBtn, NewsFooter, ButtonCeil, Share }
