import { Assets } from '../../react-native-ui-lib'
Assets.loadAssetsGroup('icons', {
  backArrow: require('../assets/icons/ic_back.png'),
  backClose: require('../assets/share/close.png'),
  logo: require('../assets/logo.png'),
  cycle: require('../assets/home/cycle.png'),
  headIcon: require('../assets/home/account.png'),
  searchIcon: require('../assets/home/ic_search_24.png'),
  icon01: require('../assets/home/icon01.png'),
  icon02: require('../assets/home/icon02.png'),
  icon03: require('../assets/home/icon03.png'),
  icon04: require('../assets/home/icon04.png'),
  icon05: require('../assets/home/icon05.png'),
  icon06: require('../assets/home/icon06.png'),
  icon07: require('../assets/home/icon07.png'),
  icon08: require('../assets/home/icon08.png'),
  arrow: require('../assets/mine/arrow.png'),
  vipIcon: require('../assets/mine/vip-icon.png'),
  vipImg: require('../assets/mine/vip.png'),
  arrowRight: require('../assets/mine/arrow-right.png'),
  card: require('../assets/pay/card.png'),
  vip: require('../assets/pay/vip.png'),
  wechat: require('../assets/pay/wechat.png'),
  select: require('../assets/icons/checked.png'),
  mine: require('../assets/icons/mine.png'),
  class: require('../assets/icons/class.png'),
  home: require('../assets/icons/home.png'),
  close: require('../assets/icons/close.png'),
  pay01: require('../assets/pay/pay01.png'),
  pay02: require('../assets/pay/pay02.png'),
  pay03: require('../assets/pay/pay03.png'),
  pay04: require('../assets/pay/pay04.png'),
  payitem01: require('../assets/pay/VIP-02.png'),
  payitem02: require('../assets/pay/VIP-03.png'),
  payitem03: require('../assets/pay/VIP-04.png'),
  payitem04: require('../assets/pay/VIP-05.png'),
  payitem05: require('../assets/pay/VIP-06.png'),
  payitem06: require('../assets/pay/VIP-07.png'),
  playerPlay: require('../assets/player/play.png'),
  playerPlayBig: require('../assets/player/play_big.png'),
  playerPausedBig: require('../assets/player/paused_big.png'),
  playerPause: require('../assets/player/pause.png'),
  playerClose: require('../assets/player/close.png'),
  playerArrowUp: require('../assets/player/arrow_up.png'),
  playerArrowDown: require('../assets/player/arrow_down.png'),
  comment: require('../assets/player/comment.png'),
  detail: require('../assets/player/detail.png'),
  attention: require('../assets/player/attention.png'),
  attention_active: require('../assets/player/attention_active.png'),
  star: require('../assets/player/star.png'),
  star_active: require('../assets/player/star_active.png'),
  share: require('../assets/player/share.png'),
  play: require('../assets/icons/play.png'),
  paused: require('../assets/icons/paused.png'),
  delete: require('../assets/icons/delete.png'),
  article_title1: require('../assets/icons/aTitle1.png'),
  article_title2: require('../assets/icons/aTitle2.png'),
  article_title3: require('../assets/icons/aTitle3.png'),
  article_title4: require('../assets/icons/aTitle4.png'),
  article_title5: require('../assets/icons/aTitle5.png')
})

/* share */
Assets.loadAssetsGroup('share', {
  close: require('../assets/share/close.png'),
  wechat: require('../assets/share/wechat.png'),
  timeline: require('../assets/share/timeline.png'),
  qq: require('../assets/share/qq.png'),
  weibo: require('../assets/share/weibo.png')
})
/* mine */
Assets.loadAssetsGroup('mine', {
  info: require('../assets/mine/info.png'),
  star: require('../assets/mine/star.png'),
  vip_center: require('../assets/mine/vip_center.png'),
  feedback: require('../assets/mine/feedback.png'),
  about: require('../assets/mine/about.png')
})
